#!/bin/bash
# 上传到GitHub的最终脚本

echo "🚀 准备上传到GitHub"
echo "===================="
echo ""
echo "📦 GitHub仓库："
echo "   https://github.com/molinarolafont487-jpg/AI-"
echo ""
echo "📁 项目文件已准备好："
echo "   dacheng-ai-academy.zip"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 上传方法（3选1）："
echo ""
echo "方法1: 使用GitHub网页上传 ⭐ 最简单"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 访问: https://github.com/molinarolafont487-jpg/AI-"
echo "2. 点击 'Add file' → 'Upload files'"
echo "3. 拖拽 dacheng-ai-academy.zip 上传"
echo "4. 或者直接拖拽 website 文件夹"
echo "5. 填写 commit 信息: '大成智改AI商学院官网'"
echo "6. 点击 'Commit changes'"
echo ""
echo "方法2: 解压后手动上传"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 解压 dacheng-ai-academy.zip"
echo "2. 访问 GitHub 仓库"
echo "3. 逐个文件夹上传"
echo ""
echo "方法3: 使用Git命令（需要GitHub已登录）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "git push -u origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 上传成功后，下一步："
echo ""
echo "1. 访问 Vercel: https://vercel.com/new"
echo "2. 导入仓库: AI-"
echo "3. ⚠️  Root Directory: website"
echo "4. 点击 Deploy"
echo ""
echo "🎉 完成！"
